name: root
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- altair=1.2.1=py_0
- asn1crypto=0.22.0=py36_0
- audioread=2.1.4=py36_2
- av=0.3.3=py36_0
- backcall=0.1.0=py_0
- backports=1.0=py36_1
- backports.functools_lru_cache=1.4=py36_1
- backports.weakref=1.0rc1=py36_1
- beautifulsoup4=4.6.0=py36_0
- blas=1.1=openblas
- bleach=1.5.0=py36_0
- blinker=1.4=py_0
- bokeh=0.12.13=py36_0
- boto3=1.6.2=py_0
- botocore=1.9.2=py_0
- bzip2=1.0.6=1
- ca-certificates=2017.11.5=0
- cairo=1.14.6=4
- certifi=2017.11.5=py36_0
- cffi=1.11.2=py36_0
- chardet=3.0.4=py36_0
- click=6.7=py_1
- cloudpickle=0.2.2=py36_4
- colour=0.1.5=py_0
- conda=4.3.31=py36_0
- conda-env=2.6.0=0
- cryptography=2.1.4=py36_0
- cycler=0.10.0=py36_0
- cython=0.25.2=py36_1
- dask-core=0.16.1=py_0
- dbus=1.10.22=0
- decorator=4.0.11=py36_0
- dill=0.2.7.1=py36_0
- docutils=0.14=py36_0
- entrypoints=0.2.3=py36_1
- et_xmlfile=1.0.1=py36_0
- eventlet=0.22.0=py_0
- expat=2.2.5=0
- fastcache=1.0.2=py36_0
- ffmpeg=2.8.6=5
- flask=0.12.2=py36_0
- flask-socketio=2.9.2=py36_0
- fontconfig=2.12.1=4
- freetype=2.7=1
- future=0.16.0=py36_0
- gensim=3.4.0=py36_0
- geos=3.6.2=1
- gettext=0.19.7=1
- giflib=5.1.4=0
- glib=2.51.4=0
- gmp=6.1.2=0
- greenlet=0.4.12=py36_0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=1
- h5py=2.7.1=py36_1
- harfbuzz=1.3.4=2
- hdf5=1.8.18=2
- heapdict=1.0.0=py36_0
- html5lib=0.9999999=py36_0
- icu=58.2=0
- idna=2.6=py36_1
- imageio=2.1.2=py36_0
- ipykernel=4.7.0=py36_0
- ipython=6.2.1=py36_1
- ipython_genutils=0.2.0=py36_0
- ipywidgets=7.0.5=py36_0
- itsdangerous=0.24=py_2
- jasper=1.900.1=4
- jdcal=1.3=py36_0
- jedi=0.10.2=py36_0
- jinja2=2.10=py36_0
- jmespath=0.9.3=py36_0
- joblib=0.11=py36_0
- jpeg=9b=2
- jsonschema=2.6.0=py36_0
- jupyter_client=5.2.1=py36_0
- jupyter_core=4.4.0=py_0
- jupyterlab=0.31.8=py36_1
- jupyterlab_launcher=0.10.5=py36_0
- keras=2.0.9=py36_0
- libedit=3.1.20170329=0
- libffi=3.2.1=3
- libgpuarray=0.7.5=0
- libiconv=1.15=0
- libpng=1.6.34=0
- librosa=0.5.1=py36_1
- libsodium=1.0.15=1
- libtiff=4.0.9=0
- libwebp=0.5.2=7
- libxcb=1.12=1
- libxml2=2.9.7=0
- locket=0.2.0=py36_1
- mako=1.0.7=py36_0
- markupsafe=1.0=py36_0
- matplotlib=2.1.0=py36_0
- mistune=0.8.3=py_0
- mock=2.0.0=py36_0
- moviepy=0.2.3.2=py36_0
- mpmath=1.0.0=py_0
- msgpack-python=0.4.8=py36_0
- nbconvert=5.3.1=py_1
- nbformat=4.4.0=py36_0
- ncurses=5.9=10
- networkx=1.11=py36_0
- ninja=1.8.2=1
- nltk=3.2.5=py_0
- notebook=5.4.1=py36_0
- numpy=1.12.1=py36_blas_openblas_200
- oauthlib=2.0.6=py_0
- olefile=0.44=py36_0
- openblas=0.2.19=2
- opencv=3.2.0=np112py36_blas_openblas_203
- openpyxl=2.5.0b1=py36_0
- openssl=1.0.2n=0
- packaging=16.8=py36_0
- pandas=0.20.3=py36_1
- pandoc=2.1=0
- pandocfilters=1.4.1=py36_0
- parso=0.2.1=py_0
- partd=0.3.8=py36_0
- patsy=0.4.1=py36_0
- pbr=3.1.1=py36_0
- pcre=8.39=0
- pexpect=4.3.1=py36_0
- pickleshare=0.7.4=py36_0
- pillow=4.2.1=py36_0
- pip=9.0.1=py36_1
- pixman=0.34.0=1
- plotly=2.0.15=py36_0
- prompt_toolkit=1.0.15=py36_0
- protobuf=3.5.1=py36_3
- psutil=5.4.0=py36_0
- ptyprocess=0.5.2=py36_0
- py4j=0.10.6=py36_1
- pycosat=0.6.3=py36_0
- pycparser=2.18=py36_0
- pydot=1.2.4=py_0
- pydotplus=2.0.2=py36_0
- pygments=2.2.0=py36_0
- pygpu=0.7.5=py36_0
- pyjwt=1.5.3=py_0
- pymc3=3.2=py36_0
- pyopenssl=17.4.0=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_4
- pysocks=1.6.8=py36_1
- pyspark=2.2.1=py36_0
- python=3.6.3=1
- python-crfsuite=0.9.2=py36_0
- python-dateutil=2.6.1=py36_0
- python-engineio=2.0.2=py_0
- python-socketio=1.8.4=py_0
- pytz=2017.3=py_2
- pywavelets=0.5.2=py36_1
- pyyaml=3.12=py36_1
- pyzmq=16.0.2=py36_3
- qt=5.6.2=3
- readline=6.2=0
- requests=2.18.4=py36_1
- requests-oauthlib=0.8.0=py36_1
- resampy=0.2.0=py36_1
- ruamel_yaml=0.11.14=py36_0
- s3transfer=0.1.13=py36_0
- scikit-image=0.13.1=py36_0
- scikit-learn=0.19.1=py36_blas_openblas_200
- scipy=0.19.1=py36_blas_openblas_202
- seaborn=0.8.1=py36_0
- send2trash=1.5.0=py_0
- setuptools=38.4.0=py36_0
- shapely=1.6.4=py36_0
- simplegeneric=0.8.1=py36_0
- sip=4.18=py36_1
- six=1.11.0=py36_1
- smart_open=1.5.6=py36_1
- sqlalchemy=1.1.13=py36_0
- sqlite=3.13.0=1
- statsmodels=0.8.0=py36_0
- sympy=1.0=py36_0
- tensorflow=1.3.0=py36_0
- terminado=0.8.1=py36_0
- testpath=0.3.1=py36_0
- theano=1.0.1=py36_1
- tk=8.5.19=2
- toolz=0.8.2=py_2
- tornado=4.5.3=py36_0
- tqdm=4.11.2=py36_0
- traitlets=4.3.2=py36_0
- tweepy=3.5.0=py36_0
- twython=3.6.0=py36_0
- urllib3=1.22=py36_0
- utm=0.4.2=py36_0
- uvloop=0.8.1=py36_0
- vega=0.4.4=py36_1
- vincent=0.4.4=py36_0
- wcwidth=0.1.7=py36_0
- webencodings=0.5=py36_0
- websockets=4.0.1=py36_0
- werkzeug=0.14.1=py_0
- wheel=0.30.0=py36_2
- widgetsnbextension=3.1.0=py36_0
- wordcloud=1.4.1=py36_0
- x264=20131217=3
- xlrd=1.1.0=py_2
- xorg-libxau=1.0.8=3
- xorg-libxdmcp=1.1.2=3
- xz=5.2.3=0
- yaml=0.1.6=0
- zeromq=4.2.1=1
- zlib=1.2.11=0
- boto=2.48.0=py36h6e4cd66_1
- bz2file=0.98=py36_0
- cudatoolkit=8.0=3
- cudnn=7.0.5=cuda8.0_0
- intel-openmp=2018.0.0=hc7b2577_8
- libgcc=7.2.0=h69d50b8_2
- libgcc-ng=7.2.0=h7cc24e2_2
- libgfortran=3.0.0=1
- libgfortran-ng=7.2.0=h9f7466a_2
- libopenblas=0.2.20=h9ac9557_4
- libstdcxx-ng=7.2.0=h7a57d05_2
- libtorch=0.1.12=nomkl_0
- llvmlite=0.20.0=py36_0
- markdown=2.6.9=py36_0
- mkl=2018.0.1=h19d6760_4
- nccl=1.3.4=cuda8.0_1
- nomkl=1.0=0
- numba=0.35.0=np112py36_0
- numexpr=2.6.4=py36_nomklh2c28f9d_0
- pomegranate=0.9.0=py36h3010b51_0
- pytorch=0.4.0=py36_cuda8.0.61_cudnn7.1.2_1
- torchvision=0.2.1=py36_1
- pip:
  - atari-py==0.1.1
  - backports.functools-lru-cache==1.4
  - box2d==2.3.2
  - box2d-kengz==2.3.3
  - bresenham==0.2
  - dask==0.16.1
  - dronekit==2.9.1
  - et-xmlfile==1.0.1
  - glfw==1.6.0
  - gym==0.9.6
  - html2text==2018.1.9
  - ipython-genutils==0.2.0
  - jdc==0.0.8
  - jupyter-client==5.2.1
  - jupyter-core==4.4.0
  - jupyterlab-launcher==0.10.5
  - lxml==4.1.1
  - monotonic==1.2
  - mujoco-py==1.50.1.56
  - prompt-toolkit==1.0.15
  - pycurl==7.43.0.1
  - pyglet==1.3.0
  - pymavlink==2.2.8
  - pyopengl==3.1.0
  - python-speech-features==0.6
  - requests-toolbelt==0.8.0
  - ruamel-yaml==0.11.14
  - seekwell==0.1
  - simplewebsocketserver==0.1.0
  - smart-open==1.5.6
  - soundfile==0.9.0.post1
  - torch==0.4.0
  - udacity-pa==0.2.7
  - wptools==0.4.7
prefix: /opt/conda

